apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-instances
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Trev2689/anubis.git'
        revision: HEAD
        directories:
          - path: 'usw2/eks-td1/vault/overlays/*-vault'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: anubis
      source:
        repoURL: 'https://github.com/Trev2689/anubis.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
      hooks:
        - name: post-sync-restart-pods
          hookType: PostSync
          manifest: |
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: restart-pods-job
            spec:
              template:
                spec:
                  containers:
                    - name: restart-pods-container
                      image: kubectl:latest
                      command: ["sh", "-c", "for ns in $(kubectl get namespaces -o=jsonpath='{.items[*].metadata.name}' | grep -E '.*-vault$'); do kubectl -n $ns get pods -l vault-active!=true -o=jsonpath='{.items[*].metadata.name}' | xargs -I{} kubectl -n $ns delete pod {}; kubectl -n $ns get pods -l vault-active=true -o=jsonpath='{.items[*].metadata.name}' | xargs -I{} kubectl -n $ns delete pod {}; done"]
                  restartPolicy: Never
