apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Trev2689/anubis.git'
    targetRevision: HEAD
    path: usw2/eks-td1/core-test/apps/kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aws-pca-issuer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
