apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://traefik.github.io/charts'
    targetRevision: v28.1.0
    chart: traefik
    helm:
      releaseName: traefik
      valueFiles:
        - $values/usw2/eks-td1/core-test/apps/values/traefik-values.yaml  # Ensure the correct path
  - repoURL: 'https://github.com/Trev2689/anubis.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
  # helm:
  #   valueFiles:
  #     - ../values/traefik-values.yaml
