apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: core-cluster-bootstrap
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: v26.1.0
    chart: traefik
    helm:
      releaseName: traefik
      valueFiles:
        - apps/values/traefik-values.yaml  # Ensure the correct path
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
  # helm:
  #   valueFiles:
  #     - ../values/traefik-values.yaml
