apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: core-cluster-bootstrap
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik/traefik
    repoURL: 'https://traefik.github.io/charts'  # Make sure to provide the correct repoURL
    targetRevision: v26.1.0
    helm:
      releaseName: traefik
      valueFiles:
      - ../values/traefik-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
  # helm:
  #   valueFiles:
  #     - ../values/traefik-values.yaml
