apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: anubis
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: v28.2.0
    chart: traefik
    helm:
      releaseName: traefik
      values: |
        deployment:
          kind: DaemonSet
        core:
          defaultRuleSyntax: v3
        logs:
          access:
            enabled: true
        ports:
          websecure:
            protocol: TCP
            nodePort: 32443
        service:
          type: NodePort
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
