apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-cabundle-configmap
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-cabundle-configmap
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "update", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-cabundle-configmap-binding
subjects:
- kind: ServiceAccount
  name: create-cabundle-configmap
  namespace: monitoring
roleRef:
  kind: Role
  name: create-cabundle-configmap
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-cabundle-configmap-job
  namespace: monitoring
spec:
  template:
    spec:
      serviceAccountName: create-cabundle-configmap
      containers:
        - name: create-cabundle-configmap
          image: 997925851768.dkr.ecr.us-west-2.amazonaws.com/alpaca-ca-bundle:2024.07.2
          env:
            - name: silo
              value: eng
            - name: namespace
              value: default
      restartPolicy: OnFailure
