apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-revision-monitor
  namespace: copenhagen-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-revision-monitor
  template:
    metadata:
      labels:
        app: controller-revision-monitor
    spec:
      containers:
      - name: controller-revision-monitor
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        args: ["bash /scripts/controller-revision-monitor.sh"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: controller-revision-monitor-scripts
