apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-updater

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-controller-revisions-delete-pods
rules:
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-controller-revisions-delete-pods-binding
subjects:
- kind: ServiceAccount
  name: vault-updater
  namespace: default
roleRef:
  kind: ClusterRole
  name: list-controller-revisions-delete-pods
  apiGroup: rbac.authorization.k8s.io
