apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tromso-vault

resources:
  - ../../base

helmCharts:
  - name: anubis-resources
    version: 0.10.0
    repo: https://trev2689.github.io/helm-charts/
    valuesFile: common-values.yaml
    releaseName: tromso-vault-anubis-resources
    namespace: tromso-vault
  


  - name: vault
    version: 0.28.0
    repo: https://helm.releases.hashicorp.com
    valuesFile: vault-values.yaml
    releaseName: tromso
    namespace: tromso-vault
