# Deploys traefik as a nodeport service, which target groups on our nlb then sends traffic to, allowing us to "bring our own" NLB.
# Manaual usage "helm install traefik traefik/traefik --create-namespace --namespace=traefik --values=traefik-values.yaml"
deployment:
  kind: DaemonSet
ports:
  websecure:
    protocol: TCP
    nodePort: 32443
service:
  type: NodePort
