apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: ism2-vault

resources:
  - ../../base

helmCharts:
  - name: anubis-resources
    version: 0.18.0
    repo: https://trev2689.github.io/helm-charts/
    valuesFile: common-values.yaml
    releaseName: ism2-vault-anubis-resources
    namespace: ism2-vault
  


  - name: vault
    version: 0.28.0
    repo: https://helm.releases.hashicorp.com
    valuesFile: vault-values.yaml
    releaseName: ism2
    namespace: ism2-vault
